
### Config for ESPHome NRF24L01 Master Node ###


# Setup
esphome:
  name: esphome-web-3514f0
  friendly_name: ESPHome NRF Master         #ESPHome Web 3515f0
  includes:
    - nrfmaster.h
    #- basic.h
  libraries:
    - SPI
    - RF24
    - nRF24L01

# Board
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  #level: NONE 

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key
ota:
  password: !secret ota_password 

# Wifi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
    
# Config for NRF_Master
custom_component:
- lambda: |-
    auto my_custom = new nrfmaster(); 
    return {my_custom};
  components:
  - id: my_custom_id



    
 
    
        
