
# ESPHome NRF Master
esphome:
  name: "nrfmaster"
  friendly_name: NRF_Master
  includes:
    - nrfmaster.h
  libraries:
    - SPI
    - RF24
    - nRF24L01
    
# Board
esp32:
  board: az-delivery-devkit-v4 #esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  #level: NONE  # Disable logs

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key
ota:
  password: !secret api_password

# Wifi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Config for NRF_Master
custom_component:
- lambda: |-
    auto my_custom = new nrfmaster();
    return {my_custom};
  components:
  - id: my_custom_id   
 
    
    
