### Config for ESPHome NRF_Master ###


# Setup
esphome:
  name: esphome-web-3514f0
  friendly_name: ESPHome Web 3515f0
  includes:
    - testone.h
  #libraries:
  #  - SPI
  #  - RF24
  #  - nRF24L01

# Board
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  #level: NONE  # Disable logs

# Enable Home Assistant API
api:
    #host: 192.168.1.51
  encryption:
    key: "mRzZ3BMML0YQ0GusREoGnq/c4GS2YCXvoh6sETzFVbI="
ota:
  password: "9e2026895a1132879bb94ec5c6c423b0"

# Wifi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
    
# Config for NRF_Master
custom_component:
- lambda: |-
    auto my_custom = new MyCustomSensor();
    return {my_custom};
  components:
  - id: my_custom_id



    
 
    
        
